# Generated by Django 5.2.11 on 2026-04-20 07:24

from django.db import migrations


def set_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={'domain': 'brainzacademy.com', 'name': 'BrainzAcademy'}
    )


def unset_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={'domain': 'example.com', 'name': 'example.com'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_gender'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(set_site, unset_site),
    ]