# Generated by Django 5.2.11 on 2026-08-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
