# Generated by Django 5.2.11 on 2026-03-29 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_pastpaper'),
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'completed_at'], name='practice_pr_user_id_edaa80_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'subject'], name='practice_pr_user_id_10eedd_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['completed_at'], name='practice_pr_complet_a6aaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['session', 'question'], name='practice_us_session_7e3ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['is_correct'], name='practice_us_is_corr_09089a_idx'),
        ),
    ]
