# Generated by Django 5.2.11 on 2026-04-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practicesession_practice_pr_user_id_edaa80_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
