# Generated by Django 5.2.11 on 2026-04-23 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_question_unique_together'),
        ('practice', '0003_practicesession_total_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1200)),
                ('is_pinned', models.BooleanField(default=False, help_text='Reserved for teacher/admin-pinned comments.')),
                ('is_hidden', models.BooleanField(default=False, help_text='Soft-delete: hides comment without removing from DB.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_comments', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.question')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['question', 'is_hidden'], name='practice_qu_questio_4b616f_idx')],
            },
        ),
    ]
