# Generated by Django 5.2.11 on 2026-03-04 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Snake_case identifier used in code, e.g. 'lesson_notes'", unique=True)),
                ('label', models.CharField(help_text='Human-readable name shown in admin panel', max_length=120)),
                ('description', models.TextField(blank=True, help_text='What this feature does — shown in admin panel')),
                ('is_enabled', models.BooleanField(default=True)),
                ('visible_to', models.CharField(choices=[('ALL', 'All users'), ('STUDENT', 'Students only'), ('TEACHER', 'Teachers only')], default='ALL', help_text="Which role this flag gates. Disabling 'TEACHER' flag still works for STUDENT views.", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lesson_notes/')),
                ('description', models.TextField(blank=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_content', models.TextField(blank=True, help_text='Raw AI text, stored so it can be rendered as HTML or later converted to a real PDF by an admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_note', to='catalog.topic')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic__name'],
            },
        ),
    ]
