# Generated by Django 5.2.11 on 2026-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a video explaining this answer', null=True),
        ),
        migrations.AddField(
            model_name='theoryanswer',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to a video walkthrough of this answer', null=True),
        ),
    ]
