# Generated by Django 5.2.11 on 2026-03-13 05:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_featureflag_lessonnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeUsageTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('STUDENT_BASIC', 'Student Basic'), ('TEACHER_PRO', 'Teacher Pro')], max_length=20)),
                ('duration', models.CharField(choices=[('MONTHLY', 'Monthly'), ('TERMLY', 'Termly (3 months)'), ('YEARLY', 'Yearly')], max_length=10)),
                ('name', models.CharField(help_text="Display name e.g. 'Student Basic — Monthly'", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Naira (NGN)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Shown on the pricing page')),
                ('features', models.TextField(blank=True, help_text="Comma-separated list of features e.g. 'Unlimited practice,Full analytics,Lesson notes'")),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are hidden from the pricing page')),
                ('paystack_plan_code', models.CharField(blank=True, help_text='Filled automatically when Paystack keys are added', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plan_type', 'price'],
                'unique_together': {('plan_type', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paystack_reference', models.CharField(blank=True, help_text='Paystack transaction reference', max_length=200)),
                ('paystack_sub_code', models.CharField(blank=True, help_text='Paystack subscription code for recurring billing', max_length=200)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='catalog.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
