# Generated by Django 5.2.11 on 2026-03-13 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_freeusagetracker_subscriptionplan_usersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freeusagetracker',
            name='test_builder_trials_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freeusagetracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='FreeTeacherTopicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_accesses', to='catalog.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_topic_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['accessed_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
