# Generated by Django 5.2.11 on 2026-03-17 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_theme_topic_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examseries',
            index=models.Index(fields=['subject', 'exam_board', 'year'], name='catalog_exa_subject_d04c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='examseries',
            index=models.Index(fields=['year'], name='catalog_exa_year_1059df_idx'),
        ),
        migrations.AddIndex(
            model_name='freeusagetracker',
            index=models.Index(fields=['user'], name='catalog_fre_user_id_f971b7_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'question_type'], name='catalog_que_subject_4fbf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='catalog_que_difficu_b6b478_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'theme'], name='catalog_top_subject_1e692e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='catalog_use_user_id_55fb22_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status', 'expires_at'], name='catalog_use_status_b1adeb_idx'),
        ),
    ]
