# Generated by Django 5.2.11 on 2026-03-20 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_examseries_catalog_exa_subject_d04c5c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnote',
            name='video_url',
            field=models.URLField(blank=True, help_text='Short video summary for this topic', null=True),
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='worksheets/')),
                ('ai_content', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Video walkthrough of worksheet solutions', null=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet', to='catalog.topic')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_worksheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic__name'],
            },
        ),
    ]
