# Generated by Django 5.2.11 on 2026-03-25 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_lessonnote_video_url_worksheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('OBJ', 'Objective'), ('THEORY', 'Theory'), ('PRACTICAL', 'Practical')], max_length=20)),
                ('question_pdf', models.FileField(blank=True, help_text='PDF of the questions', null=True, upload_to='past_papers/questions/')),
                ('answer_pdf', models.FileField(blank=True, help_text='PDF of the answers/marking scheme', null=True, upload_to='past_papers/answers/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video walkthrough URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='catalog.examseries')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_series__year', 'paper_type'],
                'indexes': [models.Index(fields=['exam_series', 'paper_type'], name='catalog_pas_exam_se_2bc42e_idx')],
                'unique_together': {('exam_series', 'paper_type')},
            },
        ),
    ]
