# Generated by Django 5.2.11 on 2026-04-08 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_pastpaper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word')], default='pdf', max_length=10)),
                ('copy_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10)),
                ('builder_mode', models.CharField(choices=[('manual', 'Manual'), ('random', 'Random')], default='manual', max_length=10)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='catalog.savedtest')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_marks', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_in_tests', to='catalog.question')),
                ('saved_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='catalog.savedtest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('saved_test', 'question')},
            },
        ),
        migrations.AddField(
            model_name='savedtest',
            name='questions',
            field=models.ManyToManyField(through='catalog.SavedTestQuestion', to='catalog.question'),
        ),
    ]
