# Generated by Django 5.2.11 on 2026-04-14 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_savedtest_savedtestquestion_savedtest_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True, help_text='What this feature does'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='visible_to',
            field=models.CharField(choices=[('ALL', 'All users'), ('STUDENT', 'Students only'), ('TEACHER', 'Teachers only')], default='ALL', help_text='Which role this flag gates.', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='ai_content',
            field=models.TextField(blank=True, help_text='Raw AI text — can be rendered as HTML or converted to PDF by an admin.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, help_text='Comma-separated list of features'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, help_text='Paystack plan code for recurring billing', max_length=100),
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_required', models.BooleanField(default=True, help_text='Uncheck to make the platform fully free for all users.')),
                ('free_daily_sessions', models.PositiveIntegerField(default=5, help_text='Daily practice sessions allowed for free users.')),
                ('free_question_limit', models.PositiveIntegerField(default=15, help_text='Max questions per session for free users.')),
                ('free_test_builder_trials', models.PositiveIntegerField(default=2, help_text='Lifetime test builder trials for free teachers.')),
                ('free_lesson_note_slots', models.PositiveIntegerField(default=5, help_text='Unique topic slots for free teachers in lesson notes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Settings',
            },
        ),
    ]
