# Generated by Django 5.2.11 on 2026-04-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_featureflag_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam_series', 'question_number', 'question_type')},
        ),
    ]
