# Generated by Django 5.2.11 on 2026-04-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_question_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_after_image',
            field=models.TextField(blank=True, default='', help_text='Question text that appears after the diagram image in the original document.'),
        ),
    ]
