# Generated by Django 5.2.11 on 2026-05-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_question_content_after_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examseries",
            name="sitting",
            field=models.CharField(
                choices=[
                    ("MAY_JUNE", "May/June"),
                    ("NOV_DEC", "Nov/Dec"),
                    ("MOCK", "Mock"),
                    ("MOCK-SERIES", "Mock Series"),
                ],
                default="MAY_JUNE",
                max_length=20,
            ),
        ),
    ]
