# Generated by Django 5.2.11 on 2026-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_alter_examseries_sitting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("OBJ", "Objective"),
                    ("ORAL_OBJ", "Oral Objective"),
                    ("THEORY", "Theory"),
                ],
                default="OBJ",
                max_length=10,
            ),
        ),
    ]
