# Generated by Django 5.2.11 on 2026-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("OBJ", "Objective"),
                    ("ORAL_ENG_OBJ", "Oral Objective"),
                    ("THEORY", "Theory"),
                ],
                default="OBJ",
                max_length=12,
            ),
        ),
    ]
