# Generated by Django 5.2.11 on 2026-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examseries",
            name="sitting",
            field=models.CharField(
                choices=[
                    ("MAY_JUNE", "May/June"),
                    ("JUNE_JULY", "June/July"),
                    ("JAN_FEB", "Jan/Feb"),
                    ("NOV_DEC", "Nov/Dec"),
                    ("MOCK", "Mock"),
                    ("MOCK-SERIES", "Mock Series"),
                ],
                default="MAY_JUNE",
                max_length=20,
            ),
        ),
    ]
