# Generated by Django 5.2.11 on 2026-09-01 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_alter_examseries_sitting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Snake_case identifier used in code, e.g. 'lesson_plan_generator'",
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name shown in admin panel",
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this feature does"),
                ),
                (
                    "is_ai_powered",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this feature makes live AI API calls (informs cost/pricing decisions).",
                    ),
                ),
                (
                    "default_pricing_mode",
                    models.CharField(
                        choices=[
                            ("FREE", "Free — always free, no trial clock"),
                            (
                                "FREE_UNTIL",
                                "Free until a set date, then requires payment",
                            ),
                            ("PAID", "Paid — requires an active paid grant"),
                        ],
                        default="PAID",
                        help_text="Starting pricing mode copied onto a school's grant when first accessed.",
                        max_length=10,
                    ),
                ),
                (
                    "default_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Starting quoted price (NGN) copied onto a school's grant when first created.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_advertised",
                    models.BooleanField(
                        default=True,
                        help_text="Shown on a school-facing 'features' page even before that school has been granted access (e.g. 'coming soon' / 'ask about this').",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "curriculum",
                    models.CharField(
                        choices=[
                            ("NIGERIAN", "Nigerian (WAEC / NECO / JAMB)"),
                            ("IGCSE", "British (IGCSE)"),
                        ],
                        default="NIGERIAN",
                        max_length=10,
                    ),
                ),
                (
                    "class_level",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS1"),
                            ("JSS2", "JSS2"),
                            ("JSS3", "JSS3"),
                            ("SS1", "SS1"),
                            ("SS2", "SS2"),
                            ("SS3", "SS3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "coverage",
                    models.TextField(
                        help_text="What this lesson covers, in the teacher's own words."
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Lesson length in minutes."),
                ),
                ("class_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "student_ability",
                    models.CharField(
                        choices=[
                            ("FAST", "Fast learners"),
                            ("MODERATE", "Moderate pace"),
                            ("SLOW", "Slow learners"),
                            ("MIXED", "Mixed ability"),
                        ],
                        default="MIXED",
                        max_length=10,
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional extra context: resources on hand, prior lesson, exam focus, etc.",
                    ),
                ),
                ("objectives", models.TextField(blank=True)),
                ("activities", models.TextField(blank=True)),
                ("timing_breakdown", models.TextField(blank=True)),
                ("assessment", models.TextField(blank=True)),
                (
                    "is_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True once AI content has been generated and accepted for this plan.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lesson_plans",
                        to="catalog.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "-created_at"],
                        name="catalog_les_teacher_35f81a_idx",
                    )
                ],
            },
        ),
    ]
