# Generated by Django 5.2.11 on 2026-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_aifeature_lessonplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonplan",
            name="school_name",
            field=models.CharField(
                blank=True,
                help_text="Shown on the generated lesson plan header. School Plan teachers get this auto-filled from their school (editable); individual teachers can enter their own or leave blank to fall back to 'Brainz Academy'.",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="lessonplan",
            name="class_level",
            field=models.CharField(
                choices=[
                    ("JSS1", "JSS1"),
                    ("JSS2", "JSS2"),
                    ("JSS3", "JSS3"),
                    ("SS1", "SS1"),
                    ("SS2", "SS2"),
                    ("SS3", "SS3"),
                    ("YEAR7", "Year 7"),
                    ("YEAR8", "Year 8"),
                    ("YEAR9", "Year 9"),
                    ("YEAR10", "Year 10"),
                    ("YEAR11", "Year 11"),
                ],
                max_length=10,
            ),
        ),
    ]
