# Generated by Django 5.2.11 on 2026-08-16 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0016_alter_examseries_sitting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Term"),
                            ("SECOND", "Second Term"),
                            ("THIRD", "Third Term"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-year", "term"],
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full arm name, e.g. 'SS2 Gold'", max_length=100
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("JSS1", "JSS1"),
                            ("JSS2", "JSS2"),
                            ("JSS3", "JSS3"),
                            ("SS1", "SS1"),
                            ("SS2", "SS2"),
                            ("SS3", "SS3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="schools.academicterm",
                    ),
                ),
            ],
            options={
                "ordering": ["level", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_class_groups",
                        to="catalog.subject",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="schools.cohort",
                    ),
                ),
            ],
            options={
                "ordering": ["cohort", "subject"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        help_text="Nigerian state the school is located in.",
                        max_length=100,
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schools_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohorts",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="academicterm",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_terms",
                to="schools.school",
            ),
        ),
        migrations.CreateModel(
            name="SchoolInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("TEACHER", "Teacher"),
                            ("STUDENT", "Student"),
                        ],
                        max_length=10,
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("max_uses", models.PositiveIntegerField(default=1)),
                ("uses_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for STUDENT invites scoped to one class. Blank for school-wide invites.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="schools.classgroup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "Entire School"),
                            ("ROLE", "By Role"),
                            ("COHORT", "By Cohort"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        blank=True,
                        choices=[("ADMIN", "Admin"), ("TEACHER", "Teacher")],
                        max_length=10,
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_memos_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memos",
                        to="schools.school",
                    ),
                ),
                (
                    "target_cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memos",
                        to="schools.cohort",
                    ),
                ),
            ],
            options={
                "ordering": ["-pinned", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name e.g. 'School Basic — Termly'",
                        max_length=100,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        choices=[("TERMLY", "Termly (3 months)"), ("YEARLY", "Yearly")],
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Naira (NGN)",
                        max_digits=10,
                    ),
                ),
                (
                    "seat_limit",
                    models.PositiveIntegerField(
                        help_text="Max combined staff + student accounts under this plan."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Shown on the school pricing page"
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of features"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive plans are hidden from the pricing page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["price"],
                "unique_together": {("name", "duration")},
            },
        ),
        migrations.CreateModel(
            name="SchoolStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("TEACHER", "Teacher")],
                        max_length=10,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRINCIPAL", "Principal"),
                            ("VICE_PRINCIPAL", "Vice Principal"),
                            ("EXAM_OFFICER", "Exam Officer"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False when staff has been removed from the school.",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["school", "user__last_name"],
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohorts_led",
                to="schools.schoolstaff",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="class_groups",
                to="schools.schoolstaff",
            ),
        ),
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("PENDING", "Pending Payment"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paystack_reference",
                    models.CharField(
                        blank=True,
                        help_text="Paystack transaction reference",
                        max_length=200,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="schools.schoolplan",
                    ),
                ),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="schools.classgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("student", "class_group")},
            },
        ),
        migrations.CreateModel(
            name="CohortEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False if the student transferred or withdrew.",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="schools.cohort",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "indexes": [
                    models.Index(
                        fields=["cohort", "is_active"],
                        name="schools_coh_cohort__77e7ec_idx",
                    )
                ],
                "unique_together": {("student", "cohort")},
            },
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["status"], name="schools_sch_status_07bb06_idx"),
        ),
        migrations.AddIndex(
            model_name="academicterm",
            index=models.Index(
                fields=["school", "is_current"], name="schools_aca_school__805043_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicterm",
            unique_together={("school", "term", "year")},
        ),
        migrations.AddIndex(
            model_name="schoolinvite",
            index=models.Index(
                fields=["school", "role"], name="schools_sch_school__1887d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolmemo",
            index=models.Index(
                fields=["school", "is_published", "-published_at"],
                name="schools_sch_school__bea5c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolstaff",
            index=models.Index(
                fields=["school", "school_role"], name="schools_sch_school__e28a2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(
                fields=["school", "academic_term"],
                name="schools_coh_school__2c0059_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(
                fields=["school", "level"], name="schools_coh_school__84ef4b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cohort",
            unique_together={("academic_term", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="classgroup",
            unique_together={("cohort", "subject")},
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["school", "status"], name="schools_sch_school__2e8551_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolsubscription",
            index=models.Index(
                fields=["status", "expires_at"], name="schools_sch_status_a97574_idx"
            ),
        ),
    ]
