# Generated by Django 5.2.11 on 2026-09-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_aifeature_lessonplan"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFeatureAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("PAID", "Paid"),
                            ("LOCKED", "Locked"),
                        ],
                        default="LOCKED",
                        max_length=10,
                    ),
                ),
                (
                    "trial_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Only used when status is TRIAL.",
                        null=True,
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Manually agreed price (NGN) for this school, distinct from the feature's default.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "paid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Only used when status is PAID. Blank = paid access does not expire until manually revoked.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_grants",
                        to="catalog.aifeature",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_access_grants",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["school", "status"],
                        name="schools_sch_school__336c6f_idx",
                    )
                ],
                "unique_together": {("school", "feature")},
            },
        ),
    ]
