"""
Django settings for examproject project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import dj_database_url
from decouple import config
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r&lhf(d=lmez(f#ene%%2o99#ze2u36xp%am(9ftc_d2+n5baz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'payments',
    'teacher',
    'corsheaders',
    'frontend',
    'rest_framework',
    'practice',
    'catalog',
    'Users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "debug_toolbar",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # ← add this first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'examproject.urls'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'catalog.context_processors.feature_flags',   # ← add this
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'feature_tags': 'catalog.templatetags.feature_tags',  # ← add this
            }
        },
    },
]

WSGI_APPLICATION = 'examproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
 'default': dj_database_url.config(
 default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
 conn_max_age=600,
 conn_health_checks=True,
 )
}

CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'locmem')
REDIS_URL     = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')
 
if CACHE_BACKEND == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'examprep',   # avoids key collisions if Redis is shared
            'TIMEOUT': 300,             # default 5 minutes
        }
    }
elif CACHE_BACKEND == 'memcached':
    CACHES = {
        'default': {
            'BACKEND':  'django.core.cache.backends.memcached.PyMemcacheCache',
            'LOCATION': os.environ.get('MEMCACHED_URL', '127.0.0.1:11211'),
            'KEY_PREFIX': 'examprep',
            'TIMEOUT': 300,
        }
    }
else:
    # Default: LocMemCache — works out of the box, no extra services needed
    CACHES = {
        'default': {
            'BACKEND':  'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'examprep-cache',
            'TIMEOUT': 300,
        }
    }
 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files configuration

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#Set up email backend
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# SESSION_COOKIE_AGE = 600
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
AUTH_USER_MODEL = 'Users.CustomUser'
# messages set up
from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

# DRF DEfault settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:5174',
]

CORS_ALLOW_CREDENTIALS = True


LOGIN_URL = '/get-otp/'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY')
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

# CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h]
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# AWS_ACCESS_KEY_ID       = os.environ.get('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY   = os.environ.get('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
# AWS_S3_REGION_NAME      = os.environ.get('AWS_S3_REGION_NAME', 'eu-west-1')
# AWS_S3_FILE_OVERWRITE   = False
# AWS_DEFAULT_ACL         = None

# if AWS_ACCESS_KEY_ID:
#     DEFAULT_FILE_STORAGE  = 'storages.backends.s3boto3.S3Boto3Storage'
#     AWS_S3_CUSTOM_DOMAIN  = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
#     MEDIA_URL             = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# ── Add these to the BOTTOM of examproject/settings.py ───────────────────────
# Remove or comment out any existing AWS S3 settings

# ── Cloudflare R2 (media storage) ────────────────────────────────────────────
CLOUDFLARE_R2_ACCESS_KEY_ID     = os.environ.get('CLOUDFLARE_R2_ACCESS_KEY_ID')
CLOUDFLARE_R2_SECRET_ACCESS_KEY = os.environ.get('CLOUDFLARE_R2_SECRET_ACCESS_KEY')
CLOUDFLARE_R2_BUCKET_NAME       = os.environ.get('CLOUDFLARE_R2_BUCKET_NAME', 'examprep-media')
CLOUDFLARE_R2_ACCOUNT_ID        = os.environ.get('CLOUDFLARE_R2_ACCOUNT_ID')

if CLOUDFLARE_R2_ACCESS_KEY_ID:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

    AWS_ACCESS_KEY_ID     = CLOUDFLARE_R2_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY = CLOUDFLARE_R2_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME = CLOUDFLARE_R2_BUCKET_NAME
    AWS_S3_ENDPOINT_URL   = f'https://{CLOUDFLARE_R2_ACCOUNT_ID}.r2.cloudflarestorage.com'
    AWS_S3_REGION_NAME    = 'auto'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL       = None
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_S3_SIGNATURE_VERSION = 's3v4'

    # Public URL for serving files
    # Set this to your R2 public bucket URL or custom domain
    CLOUDFLARE_R2_PUBLIC_URL = os.environ.get(
        'CLOUDFLARE_R2_PUBLIC_URL',
        f'https://pub-{CLOUDFLARE_R2_ACCOUNT_ID}.r2.dev'
    )
    MEDIA_URL = f'{CLOUDFLARE_R2_PUBLIC_URL}/'
else:
    # Local dev fallback
    MEDIA_URL  = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# ── Brevo (transactional email) ───────────────────────────────────────────────
BREVO_API_KEY = os.environ.get('BREVO_API_KEY')

if BREVO_API_KEY:
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {
        'BREVO_API_KEY': BREVO_API_KEY,
    }
else:
    # Local dev — print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'ExamPrep <noreply@examprep.ng>')
SERVER_EMAIL       = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@examprep.ng')

# ── Security (production only) ────────────────────────────────────────────────
if not DEBUG:
    SECURE_PROXY_SSL_HEADER     = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT         = True
    SESSION_COOKIE_SECURE       = True
    CSRF_COOKIE_SECURE          = True
    SECURE_BROWSER_XSS_FILTER  = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    CSRF_TRUSTED_ORIGINS        = [
        f'https://{h}' for h in ALLOWED_HOSTS if h and h not in ('localhost', '127.0.0.1')
    ]

# ── Static files (WhiteNoise) ─────────────────────────────────────────────────
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'